### ISSUE TITLE
Background image glitches 20% of the way down

### ISSUE THREAD

**Issue by ZombieProtectionAgency** [adamz01h/wow_peggle#7]
![image](https://user-images.githubusercontent.com/9204874/32704764-a0d40cfe-c7d8-11e7-85fd-02da8b799a45.png)

**Comment by adamz01h** [comment]
Im not seeing the glitch here....

**Comment by ZombieProtectionAgency** [comment]
Sorry for the SUPER late reply. Somehow I missed the notification. The background texture looks normal/smokey near the top and the bottom half is just lines like the last row of pixels was just repeated vertically until it bottomed out.

I still havent tracked down where that particular texture comes from but commenting the body of the `re()` method seems to break rendering  enough to emphasize it. It ends up making the background look like this

![image](https://user-images.githubusercontent.com/9204874/53303317-f61d1000-3836-11e9-9e88-0ceb3a08b0b7.png)

I will keep looking

**Comment by Andy1210** [comment]
Its coming from the WindowBackground.blp file. Its a 64x64 tile. Its set to size 128, and it should repeat itself on the whole background but somehow it just repeating horizontally.
We can maybe stretch the tile instead of repeat. Like that we will have a gray background with blurry texture (cuz of the scale) it doesn't look bad, better than in the current state. I couldn't figure out why its not rendered properly.
